### ISSUE TITLE
Lycanites mobs - Just Monitoring

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [P3rf3ctXZer0/MC-1.12.2-xLPGx#13]
@Thutmose and @Lycanite
Let say this right away I don't fully know or understand how to code and I certainly do not fully understand what @Thutmose has stated but I do understand Lag and I do understand graphs and based on the graph that @Thutmose has shown me it is most likely necessary to find a way to redo the Lycanites mobs for performance sake. @Thutmose please explain to @Lycanite in geek speak I know I will not fully comprehend.

**Comment by P3rf3ctXZer0** [comment]
@Lycanite I fully love your mod and I am not asking for a miracle I am asking for a start. No rush just needs to happen.

**Comment by Thutmose** [comment]
I don't know anything about his mods, and it is possibly a vanilla issue, my rendering and ai code is entirely separate from vanilla stuff, so is written completely differently.  

The main thing I noticed was that in JMC profiles, the lycanitesmobs was using up the majority of the memory allocation, and a large portion of the CPU time, for both tick and render, but given that there were more of those mobs than vanilla mobs, or any not-pokemobs, it could just be something vanilla that my mobs do not account for.

The tick part was mostly collision checks during movement, which scales with cross-section of the mob, which would explain the larger contribution there, due to the larger mobs, this will not be easy to reduce at all, I don't have many large mobs, which is why it isn't as much of a concern for mine.

It is probably not easy to re-do them without a complete re-write, which I did on my mobs a few years ago.

**Comment by Lycanite** [comment]
The collision checks during movement has just very recently been fixed (update 1.18.1.1), it was mostly caused by large mobs in which case I've made a change to cap the box used for path navigation as large mobs don't really move around much anyway so them getting stuck in small areas isn't really a problem, this should have a massive impact on performance. On top of that I noticed that large lava mobs where hammering performance when constantly checking if they where in lava, by applying the same reduced detection box this speed things up a lot and on top of that I also found that ranged mobs where constantly updating their pathing to get to their target on each tick, I've since added a delay to this to match melee mobs greatly speeding things up.

For example, before this fix 1 Umber Lobber (Huuuuge lava mob) would completely lock up entities and eventually the game. After the fix 10 can be spawned in an area and the game remains fully playable, there are the occasional overloaded warnings every couple of minutes or so but this is due to so many projectiles but 10 Umber Lobbers is not a standard case at all. This should also greatly improve the bosses. Essentially any mob has its pathing box capped at 3x3x3 now allowing large mobs to navigate open areas but get stuck in small areas where they don't really move around in anyway.

If you find any spikes in diagnostics with the latest updates please send them my way and I'll see what I can do for performance.

For rendering, the code if as efficient as I can get it, but it is mostly just basic obj rendering and performs fine on mid range systems, but again, if you can send me any areas that are hammering performance I'll see what I can do to fix things.

I've only recently started really using VisualVM myself where I can really debug this stuff now so I will be taking a look at performance more and more over time but hopefully these fixes should make a major difference.

**Comment by P3rf3ctXZer0** [comment]
@Lycanite you are most definitely my favorite modder along with @Thutmose I will keep this in mind thank you so much for your patience with my comments again I meant no offense and I appreciate everything you explained.

**Comment by Lycanite** [comment]
@P3rf3ctXZer0 No probs and no offense taken at all, all feedback is important and performance is something that I'd like to get on top of. :)
